import type { VerificationMethod } from "@/types/customer-form";
import type { Gender, NcbGrade } from "@/types/customer-lead";
import type { CollateralType, LoanPurpose, RefinanceStatus } from "@/types/ratebook";

export type CustomerLeadOpportunity = {
  id: string;
  leadId: string;
  firstName: string;
  lastName: string;
  phone: string;
  idCardNumber: string;
  ncbGrade: NcbGrade | null;
  verificationMethod: VerificationMethod;
  gender: Gender | null;
  birthDate: string | null;
  loanPurpose: LoanPurpose | null;
  collateralType: CollateralType | null;
  refinanceStatus: RefinanceStatus | null;
  existingFinanceCompany: string | null;
  licensePlateNumber: string | null;
  licensePlateProvince: string | null;
  chassisNumber: string | null;
  brandModel: string | null;
  carBrand: string | null;
  carModel: string | null;
  carYear: string | null;
  carCondition: string | null;
  carDoors: string | null;
  carType: string | null;
  carEngineCc: string | null;
  carTransmission: string | null;
  carBodyType: string | null;
  carSubModel: string | null;
  selectedProductId: string | null;
  requestedAmount: string | null;
  wantsWheelCard: "yes" | "no" | null;
  hasPpi: "yes" | "no" | null;
  installmentTerm: string | null;
  possessionDate: string | null;
  carInsuranceExpiry: string | null;
  carInsuranceCompany: string | null;
  compulsoryExpiry: string | null;
  compulsoryBundledWithCarInsurance: boolean;
  compulsoryCompany: string | null;
  createdAt: string;
  updatedAt: string;
};
